openapi: 3.0.0
info:
  title: TrainSystem API
  description: TrainSystem Admin API for SIwZ project.
  version: 0.0.1
servers:
  - url: http://localhost:5000/api
paths:
  /admin/stops:
    get:
      tags:
        - Stop
      summary: Returns a list of Stops.
      responses:
        '200':    # status code
          description: A JSON array of Stops.
          content:
            application/json:
              schema: 
                type: array
                items:
                  $ref: '#/components/schemas/Stop'
    post:
      tags:
        - Stop
      summary: Creates new Stop.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StopForm'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Stop'
                
    patch:
      tags:
        - Stop
      summary: Modify Stop with given id.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Stop'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Stop'
                
  /admin/stops/{id}:
    parameters:
      - $ref: '#/components/parameters/id'
    get:
      tags:
        - Stop
      summary: Return Stop with given id.
      responses:
        '200':
          description: Stop object.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Stop'
    
    delete:
      tags:
        - Stop
      summary: Delets Stop with given id.
      responses:
        '200':
          description: Ok
  /admin/routes:
    get:
      tags:
        - Route
      summary: Returns a list of Routes.
      responses:
        '200':    # status code
          description: A JSON array of Routes.
          content:
            application/json:
              schema: 
                type: array
                items:
                  $ref: '#/components/schemas/Route'
    post:
      tags:
        - Route
      summary: Creates new Route.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RouteForm'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RoutePatch'
                
    patch:
      tags:
        - Route
      summary: Modify Route with given id.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RoutePatch'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RoutePatch'
                
  /admin/routes/{id}:
    parameters:
      - $ref: '#/components/parameters/id'
    get:
      tags:
        - Route
      summary: Returns Route with given id.
      responses:
        '200':
          description: Route object.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RoutePatch'
    
    delete:
      tags:
        - Route
      summary: Deletes Route with given id.
      responses:
        '200':
          description: Ok
  /admin/discounts:
    get:
      tags:
        - Discount
      summary: Returns a list of Discounts.
      responses:
        '200':    # status code
          description: A JSON array of Discounts.
          content:
            application/json:
              schema: 
                type: array
                items:
                  $ref: '#/components/schemas/Discount'
                  
    post:
      tags:
        - Discount
      summary: Creates new Discount.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DiscountForm'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Discount'

    patch:
      tags:
        - Discount
      summary: Modify Discount with given id.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Discount'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Discount'

  /admin/discounts/{id}:
    parameters:
      - $ref: '#/components/parameters/id'
    get:
      tags:
        - Discount
      summary: Return Discount with given id.
      responses:
        '200':
          description: Discount object.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Discount'

    delete:
      tags:
        - Discount
      summary: Deletes Discount with given id.
      responses:
        '200':
          description: Ok
  /admin/trains:
    get:
      tags:
        - Train
      summary: Returns a list of Trains.
      responses:
        '200':    # status code
          description: A JSON array of Discounts.
          content:
            application/json:
              schema: 
                type: array
                items:
                  $ref: '#/components/schemas/Train'
                  
    post:
      tags:
        - Train
      summary: Creates new Train.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TrainForm'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Train'
                
    patch:
      tags:
        - Train
      summary: Modify Train with given id.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Train'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Train'
                
  /admin/trains/{id}:
    parameters:
      - $ref: '#/components/parameters/id'
    get:
      tags:
        - Train
      summary: Return Train with given id.
      responses:
        '200':
          description: Train object.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Discount'

    delete:
      tags:
        - Train
      summary: Deletes Train with given id.
      responses:
        '200':
          description: Ok 
  /admin/rides:
    get:
      tags:
        - Ride
      summary: Returns a list of Rides.
      responses:
        '200':    # status code
          description: A JSON array of Discounts.
          content:
            application/json:
              schema: 
                type: array
                items:
                  $ref: '#/components/schemas/Ride'
    post:
      tags:
        - Ride
      summary: Creates new Ride.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RideForm'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ride'                          
  /admin/rides/{id}:
    parameters:
      - $ref: '#/components/parameters/id'
    get:
      tags:
        - Ride
      summary: Returns Ride object with given id.
      responses:
        '200':
          description: Ride object.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ride'
    patch:
      tags:
        - Ride
      summary: Modify Ride with given id.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RideForm'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ride'
    delete:
      tags:
        - Ride
      summary: Deletes Ride with given id.
      responses:
        '200':
          description: Ok 
  /admin/tickets:
    get:
      tags:
        - Tickets
      summary: Returns all tickets connected with given user Id.
      parameters: 
        - name: userId
          in: query
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Ticket'
  /admin/ticket/{id}:
    delete:
      tags:
        - Tickets
      summary: Revokes ticket with given id.
      parameters: 
        - $ref: '#/components/parameters/id'
      responses:
        '200':
          description: Ok
  /ride:
    get:
      tags: 
        - TicketsBooking
      parameters:
        - $ref: '#/components/parameters/from'
        - $ref: '#/components/parameters/to'
        - $ref: '#/components/parameters/date'
        - $ref: '#/components/parameters/routeId'
      responses:
        '200':
          description: List of matching Rides
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Ride'
  /stops:
    get:
      tags: 
        - TicketsBooking
      responses:
        '200':
          description: List of all TrainStops
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Stop'
  /routes:
    get:
      tags: 
        - TicketsBooking
      responses:
        '200':
          description: List of all routes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Route'
  /tickets/ride/{id}:
    parameters:
      - $ref: '#/components/parameters/id'
    get:
      tags: 
        - TicketsBooking
      responses:
        '200':
          description: List of available seats for ride with given id
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Seat'       
components:
  parameters:
    id:
      name: id
      in: path
      description: Numeric ID of related object
      required: true
      schema:
        type: integer
    routeId:
      name: route
      in: path
      description: Route id
      required: true
      schema:
        type: integer
    rideId:
      name: route
      in: path
      description: Ride id
      required: true
      schema:
        type: integer
    from:
      name: from
      in: query
      description: ID of first TrainStop
      schema:
        type: integer
    to:
      name: to
      in: query
      description: ID of last TrainStop
      schema:
        type: integer
    date:
      name: date
      in: query
      description: departure date
      schema:
        type: string
  schemas:
    Seat:
      type: object
      properties:
        Wagon:
          type: integer
        SeatNo:
          type:
            integer
    StopForm:
      type: object
      properties:
        Name:
          type: string
        City:
          type: string
    Stop:
      type: object
      properties:
        Id:
          type: integer
        Name:
          type: string
        City:
          type: string
    RouteStop:
      type: object
      properties:
        No:
          type: integer
        Stop:
          $ref: '#/components/schemas/Stop'
    Route:
      type: object
      properties:
        Id:
          type: integer
        Name:
          type: string
        Stops:
          type: array
          items:
            $ref: '#/components/schemas/RouteStop'
    RouteStopForm:
      type: object
      properties:
        StopId:
          type: integer
        StopNo:
          type: integer
        HoursDiff:
          type: integer
        MinutesDiff:
          type: integer
    RouteForm:
      type: object
      properties:
        Name:
          type: string
        Stops:
          type: array
          uniqueItems: true
          minItems: 4
          items:
            $ref: '#/components/schemas/RouteStopForm'
    RoutePatch:
      type: object
      properties:
        Id:
         type: integer
        Name:
          type: string
        Stops:
          type: array
          uniqueItems: true
          minItems: 4
          items:
            $ref: '#/components/schemas/RouteStopForm'
    DiscountForm:
      type: object
      properties:
        Type:
          type: string
        Value:
          type: integer
        ValueType:
          type: integer
          description:  0 - Percentage, 1 - Flat
    Discount:
      type: object
      properties:
        Id:
          type: integer
        Type:
          type: string
        Value:
          type: integer
        ValueType:
          type: integer
          description:  0 - Percentage, 1 - Flat
    Train:
      type: object
      properties:
        Id:
          type: integer
        Name:
          type: string
        Type:
          type: integer
          description:  0 - Interstitial, 1 - Open Coach
        Seats:
          type: integer
        Wagons:
          type: integer
    TrainForm:
      type: object
      properties:
        Name:
          type: string
        Type:
          type: integer
          description:  0 - Interstitial, 1 - Open Coach
        Seats:
          type: integer
        Wagons:
          type: integer
    Ride:
      type: object
      properties:
        Id:
          type: integer
        Route:
          $ref: '#/components/schemas/Route'
        StartTime:
          type: string
        Train:
          $ref: '#/components/schemas/Train'
        FreeTickets:
          type: integer
    RideForm:
      type: object
      properties:
        RouteId:
          type: integer
        StartTime:
          type: string
        TrainId:
          type: integer
    Ticket:
      type: object
      properties:
        Id:
          type: integer
        Ride:
          $ref: '#/components/schemas/Ride'
        Price:
          type: integer
          description: Price after applying discount
        UserId:
          type: integer
        From:
          $ref: '#/components/schemas/Stop'
        To:
          $ref: '#/components/schemas/Stop'
        Train:
          $ref: '#/components/schemas/Train'
        WagonNo:
          type: integer
        SeatNo:
          type: integer