swagger: '2.0'
info:
  title: TrainSystem API
  description: TrainSystem API for SIwZ project.
  version: 1.0.0
host: "localhost:5000"
basePath: /api
schemes:
  - http
  
parameters:
  id:
    in: path
    name: id
    type: integer
    required: true
    description: Numeric ID of related object

paths:
  /admin/stops:
    get:
      tags:
        - Admin/Stops
      summary: Returns a list of Stops.
      description: Defauls trainstop endpoint, returns all train stops.
      responses:
        200:
          description: OK
    post:
      tags: 
        - Admin/Stops
      summary: Creates new Stop.
      description: Creates new Stop from posted data.
      responses:
        200:
          description: OK
        400:
          description: Wrong request data
  /admin/stops/{id}:
    parameters:
      - $ref: '#/parameters/id'
    get:
      tags: 
        - Admin/Stops
      summary: Returns Stop with the given Id.
      responses:
        200:
          description: OK
        400:
          description: Stop not found.
    delete:
      tags: 
        - Admin/Stops
      summary: Removes Stop with the given Id.
      responses:
        200:
          description: OK
    patch:
      tags: 
        - Admin/Stops
      summary: Modifies Stop with
      responses:
        200:
          description: OK
  /admin/trains:
    get:
      tags:
        - Admin/Trains
      summary: Return list of all Trains.
      responses:
        200:
          description: OK
    post:
      tags:
        - Admin/Trains
      summary: Creates new Train.
      responses:
        200:
          description: OK
  /admin/trains/{id}:
    parameters:
      - $ref: '#/parameters'
    get:
      tags:
        - Admin/Trains
      summary: Returns Train with given id.
      responses:
        200:
          description: OK
    patch:
      tags:
        - Admin/Trains
      summary: Modifies Train with the given id.
      responses:
        200:
          description: OK
    delete:
      tags:
        - Admin/Trains
      summary: Removes Train with the given id.
      responses:
        200:
          description: OK
  /admin/routes:
    get:
      tags:
        - Admin/Routes
      summary: Returns list of all Routes.
      responses:
        200:
          description: OK
    post:
      tags:
        - Admin/Routes
      summary: Creates new Route.
      responses:
        200:
          description: OK
  /admin/routes/{id}:
    parameters: 
    - $ref: '#/parameters/id'
    get:
      tags:
        - Admin/Routes
      summary: Returns Route with the given id.
      responses:
        200:
          description: OK
    patch:
      tags:
        - Admin/Routes
      summary: Modifies Route with the given id.
      responses:
        200:
          description: OK
    delete:
      tags:
        - Admin/Routes
      summary: Removes Route with the given id.
      responses:
        200:
          description: OK
  /admin/discounts:
    get:
      tags:
        - Admin/Discounts
      summary: Returns list of all Discounts.
      responses:
        200:
          description: OK
    post:
      summary: Creates new Discount.
      responses:
        200:
          description: OK
  /admin/discounts/{id}:
    get:
      tags:
        - Admin/Discounts
      summary: Returns Discount with given id.
      responses:
        200:
          description: OK
    patch:
      tags:
        - Admin/Discounts
      summary: Modifies Discount with the given id.
      responses:
        200:
          description: OK
    delete:
      tags:
        - Admin/Discounts
      summary: Removes Discount with the given id.
      responses:
        200:
          description: OK
          
