version: "3.0"
services:
    server:
        depends_on:
            - database
        build:
            context: ./server
        ports:
            - 5000:5000
        restart: always
        environment:
            - TRAINS_DB=Host=database;Database=TrainSystem;Username=admin;Password=admin1
            - ASPNETCORE_URLS=http://+:5000
            - ASPNETCORE_ENVIRONMENT=Production

    client:
        depends_on:
            - server
        build:
            context: ./client
        restart: always
        environment:
            - API_URL=http://localhost:5000/api/
            - CONFIG_VARS=API_URL
        ports:
            - 8000:80

    database:
        image: postgres:latest
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_PASSWORD=admin1
            - POSTGRES_USER=admin
            - POSTGRES_DB=TrainSystem

volumes:
    database:
