version: "3.0"
services:
  server:
    build:
      context: ./server
    ports:
      - 5000:5000
      - 5001:5001
    restart: always
  database:
    image: mongo:latest
    #environment:
    #  MONGO_INITDB_ROOT_USERNAME: root
    #  MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    restart: always
  database-web:
    image: mongo-express
    #environment:
    #  ME_CONFIG_MONGODB_ADMINUSERNAME: root
    #  ME_CONFIG_MONGODB_ADMINPASSWORD: example
    ports:
      - 8081:8081
    restart: always

