version: "3.0"
services:
    server:
        depends_on:
            - database
        build:
            context: ./server
        ports:
            - 5000:5000
        restart: always
        environment:
            - TRAINS_DB=mongodb://database:27017
            - ASPNETCORE_URLS=http://+:5000
            - ASPNETCORE_ENVIRONMENT=Production

    database:
        image: mongo:latest
        restart: always

    database-web:
        depends_on:
            - database
        image: mongo-express
        ports:
            - 8081:8081
        environment:
            - ME_CONFIG_MONGODB_SERVER=database
        restart: always
        volumes:
            - database:/data/db

    postwoman:
        depends_on:
            - server
        image: liyasthomas/postwoman
        ports:
            - 3000:3000
volumes:
    database:
