// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Server.Database;

namespace Server.Migrations
{
    [DbContext(typeof(TrainSystemContext))]
    [Migration("20200425151904_Seed_Ride")]
    partial class Seed_Ride
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Server.Models.Discount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:IdentitySequenceOptions", "'3', '1', '', '', 'False', '1'")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.Property<int>("ValueType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Discounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Type = "ExampleFlat",
                            Value = 2,
                            ValueType = 1
                        },
                        new
                        {
                            Id = 2,
                            Type = "ExamplePercentage",
                            Value = 5,
                            ValueType = 0
                        });
                });

            modelBuilder.Entity("Server.Models.Ride", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:IdentitySequenceOptions", "'5', '1', '', '', 'False', '1'")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("FreeTickets")
                        .HasColumnType("integer");

                    b.Property<int>("RouteId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("TrainId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RouteId");

                    b.HasIndex("TrainId");

                    b.ToTable("Rides");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FreeTickets = 300,
                            RouteId = 1,
                            StartTime = new DateTime(2020, 4, 25, 17, 19, 4, 361, DateTimeKind.Local).AddTicks(5905),
                            TrainId = 1
                        },
                        new
                        {
                            Id = 2,
                            FreeTickets = 400,
                            RouteId = 2,
                            StartTime = new DateTime(2020, 4, 25, 17, 19, 4, 361, DateTimeKind.Local).AddTicks(7456),
                            TrainId = 2
                        },
                        new
                        {
                            Id = 3,
                            FreeTickets = 150,
                            RouteId = 3,
                            StartTime = new DateTime(2020, 4, 25, 17, 19, 4, 361, DateTimeKind.Local).AddTicks(7503),
                            TrainId = 3
                        },
                        new
                        {
                            Id = 4,
                            FreeTickets = 200,
                            RouteId = 4,
                            StartTime = new DateTime(2020, 4, 25, 17, 19, 4, 361, DateTimeKind.Local).AddTicks(7508),
                            TrainId = 4
                        });
                });

            modelBuilder.Entity("Server.Models.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("character varying(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("character varying(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Server.Models.Route", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:IdentitySequenceOptions", "'5', '1', '', '', 'False', '1'")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Routes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Rzeszow-Wroclaw"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Krakow-Warszawa"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Plaszow-Airport"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Rzeszow-Warsaw"
                        });
                });

            modelBuilder.Entity("Server.Models.StopToRoute", b =>
                {
                    b.Property<int>("RouteId")
                        .HasColumnType("integer");

                    b.Property<int>("TrainStopId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("StopNo")
                        .HasColumnType("integer");

                    b.HasKey("RouteId", "TrainStopId");

                    b.HasIndex("TrainStopId");

                    b.ToTable("StopsToRoutes");

                    b.HasData(
                        new
                        {
                            RouteId = 1,
                            TrainStopId = 5,
                            ArrivalTime = new DateTime(2020, 4, 25, 17, 19, 4, 356, DateTimeKind.Local).AddTicks(1192),
                            StopNo = 1
                        },
                        new
                        {
                            RouteId = 1,
                            TrainStopId = 7,
                            ArrivalTime = new DateTime(2020, 4, 25, 17, 19, 4, 361, DateTimeKind.Local).AddTicks(2946),
                            StopNo = 2
                        },
                        new
                        {
                            RouteId = 1,
                            TrainStopId = 6,
                            ArrivalTime = new DateTime(2020, 4, 25, 17, 19, 4, 361, DateTimeKind.Local).AddTicks(2997),
                            StopNo = 3
                        },
                        new
                        {
                            RouteId = 2,
                            TrainStopId = 1,
                            ArrivalTime = new DateTime(2020, 4, 25, 17, 19, 4, 361, DateTimeKind.Local).AddTicks(3004),
                            StopNo = 1
                        },
                        new
                        {
                            RouteId = 2,
                            TrainStopId = 4,
                            ArrivalTime = new DateTime(2020, 4, 25, 17, 19, 4, 361, DateTimeKind.Local).AddTicks(3008),
                            StopNo = 2
                        },
                        new
                        {
                            RouteId = 3,
                            TrainStopId = 2,
                            ArrivalTime = new DateTime(2020, 4, 25, 17, 19, 4, 361, DateTimeKind.Local).AddTicks(3012),
                            StopNo = 1
                        },
                        new
                        {
                            RouteId = 3,
                            TrainStopId = 1,
                            ArrivalTime = new DateTime(2020, 4, 25, 17, 19, 4, 361, DateTimeKind.Local).AddTicks(3017),
                            StopNo = 2
                        },
                        new
                        {
                            RouteId = 3,
                            TrainStopId = 3,
                            ArrivalTime = new DateTime(2020, 4, 25, 17, 19, 4, 361, DateTimeKind.Local).AddTicks(3021),
                            StopNo = 3
                        },
                        new
                        {
                            RouteId = 4,
                            TrainStopId = 5,
                            ArrivalTime = new DateTime(2020, 4, 25, 17, 19, 4, 361, DateTimeKind.Local).AddTicks(3025),
                            StopNo = 1
                        },
                        new
                        {
                            RouteId = 4,
                            TrainStopId = 2,
                            ArrivalTime = new DateTime(2020, 4, 25, 17, 19, 4, 361, DateTimeKind.Local).AddTicks(3029),
                            StopNo = 2
                        },
                        new
                        {
                            RouteId = 4,
                            TrainStopId = 1,
                            ArrivalTime = new DateTime(2020, 4, 25, 17, 19, 4, 361, DateTimeKind.Local).AddTicks(3033),
                            StopNo = 3
                        },
                        new
                        {
                            RouteId = 4,
                            TrainStopId = 4,
                            ArrivalTime = new DateTime(2020, 4, 25, 17, 19, 4, 361, DateTimeKind.Local).AddTicks(3037),
                            StopNo = 4
                        });
                });

            modelBuilder.Entity("Server.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("DiscountId")
                        .HasColumnType("integer");

                    b.Property<int>("FromId")
                        .HasColumnType("integer");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.Property<int>("RideId")
                        .HasColumnType("integer");

                    b.Property<int>("SeatNo")
                        .HasColumnType("integer");

                    b.Property<int>("ToId")
                        .HasColumnType("integer");

                    b.Property<string>("TrainName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WagonNo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DiscountId");

                    b.HasIndex("FromId");

                    b.HasIndex("RideId");

                    b.HasIndex("ToId");

                    b.HasIndex("UserId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("Server.Models.Train", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:IdentitySequenceOptions", "'5', '1', '', '', 'False', '1'")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Seats")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<int>("Wagons")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Trains");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "ICC1",
                            Seats = 60,
                            Type = 0,
                            Wagons = 5
                        },
                        new
                        {
                            Id = 2,
                            Name = "ICC2",
                            Seats = 40,
                            Type = 0,
                            Wagons = 10
                        },
                        new
                        {
                            Id = 3,
                            Name = "REG1",
                            Seats = 30,
                            Type = 1,
                            Wagons = 5
                        },
                        new
                        {
                            Id = 4,
                            Name = "REG2",
                            Seats = 40,
                            Type = 1,
                            Wagons = 5
                        });
                });

            modelBuilder.Entity("Server.Models.TrainStop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:IdentitySequenceOptions", "'8', '1', '', '', 'False', '1'")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TrainStops");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Cracow",
                            Name = "Main train station"
                        },
                        new
                        {
                            Id = 2,
                            City = "Cracow",
                            Name = "Plaszow"
                        },
                        new
                        {
                            Id = 3,
                            City = "Cracow",
                            Name = "Airport"
                        },
                        new
                        {
                            Id = 4,
                            City = "Warsaw",
                            Name = "Main train station"
                        },
                        new
                        {
                            Id = 5,
                            City = "Rzeszow",
                            Name = "Main train station"
                        },
                        new
                        {
                            Id = 6,
                            City = "Wrocalw",
                            Name = "Main train station"
                        },
                        new
                        {
                            Id = 7,
                            City = "Katowice",
                            Name = "Main train station"
                        });
                });

            modelBuilder.Entity("Server.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("character varying(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("character varying(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("character varying(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasColumnType("character varying(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Server.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Server.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Server.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Server.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Server.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Models.Ride", b =>
                {
                    b.HasOne("Server.Models.Route", "Route")
                        .WithMany()
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Models.Train", "Train")
                        .WithMany()
                        .HasForeignKey("TrainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Models.StopToRoute", b =>
                {
                    b.HasOne("Server.Models.Route", "Route")
                        .WithMany()
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Models.TrainStop", "TrainStop")
                        .WithMany()
                        .HasForeignKey("TrainStopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Models.Ticket", b =>
                {
                    b.HasOne("Server.Models.Discount", "Discount")
                        .WithMany()
                        .HasForeignKey("DiscountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Models.TrainStop", "From")
                        .WithMany()
                        .HasForeignKey("FromId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Models.Ride", "Ride")
                        .WithMany()
                        .HasForeignKey("RideId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Models.TrainStop", "To")
                        .WithMany()
                        .HasForeignKey("ToId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
